version: 2
sources:
    - name: datafeed_shared_schema
      database: "{{('dev_db')}}"
      schema: public
      tables:
        - name: stg_customerdata
        - name: stg_order
          columns:
            - name: id
              tests:
              - unique
              - not_null
            - name: status
              tests:
                - accepted_values:
                    values: ['placed', 'shipped', 'completed', 'returned', 'return_pending',return]
        - name: emp
        - name: customers
        - name: stg_payment
        